### ISSUE TITLE
Proposed RFC Feature: Navigation Gem that uses Recast/Detour open source library

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/sig-simulation#10]
### Summary

O3DE lacks an open source solution for navigation pathfinding. This RFC proposes to use an existing open source library ([Recast](https://github.com/recastnavigation/recastnavigation)) that is used throughout in the gaming industry and integrate it as a gem into O3DE.

O3DE Recast Navigation Gem will support:

- Run-time navigation mesh calculation
- Basic navigation path calculation
- World tiling (required for large world support)

A working prototype is available here: https://github.com/AMZN-Olex/RecastNavigationO3DE

### What is the relevance of this feature?

O3DE lacks an open source solution for navigation pathfinding. Legacy path finding was not ported to O3DE. Legacy path finding (which was CryEngine 3 carry over) is likely unusable without a good amount of work. Additionally, the legacy path finding solution lacks modern path finding features, such as runtime baking and world tiling, which are necessary for large world support.

### Feature design description

Recast Gem will provide the following components that wrap an existing Recast functionality.

- Navigation Mesh Surveyor component (PhysX gem unbounded shape overlap test) that collects world data for the navigation mesh from physical meshes in the world. By separating the collector from the navigation mesh processor, users can extend their worlds by providing navigation mesh data through other custom means and components. This will also help us write good unit tests by providing test data into the navigation mesh component.
- Navigation Mesh component that processes triangle data into Recast data
- Navigation Detour component that provides API to find paths within the data provided by Navigation Mesh component

### Terms

- Navigation Mesh is a data structure that defines walkable paths and provides a way to query for a path between two points within the navigation mesh volume.
- Navigation Tile is a subset or a larger navigation mesh structure. It is a vertical column of a configurable size that breaks up a large world into smaller parts to enable faster processing and faster updates in large worlds.
- Navigation Crowd is a collection of moving agents whose movements are controlled by the Recast Navigation library. These agents navigate together, towards the same goal or different goals while avoiding intersecting each other.
- Navigation Agent is usually a Non-Player Character within a Navigation Crowd that has a configurable acceleration and speed, and is assigned a target world position as its destination. Its movement is controlled by Recast Navigation gem.
- Navigation World is the volume within a level that Recast Navigation gem is aware of to build the navigation data that calculates walkable paths and obstacles within that volume.
- Recast - the open source library used to provide navigation functionality.
- Detour - portion of Recast library that performs path calculations within the navigation mesh.

#### Navigation Mesh Component
- Sets the configuration for the navigation mesh. This include agent size, height, etc.
- Calculates the navigation mesh given a set of triangle data.
- Capable of saving/loading the navigation data to a file asset. (Thus, effectively allowing either static or dynamic mode of calculating the navigation mesh.)
- Editor flavors are capable of calculating the mesh in the Editor for debugging.
- Navigation Mesh Component requires a Navigation Mesh Surveyor Component, see below.

![image](https://user-images.githubusercontent.com/5432499/168396623-9068e3dc-276f-4965-9575-9492bd444a59.png)

#### Navigation Mesh Surveyor Component
- This component is responsible for collecting the triangle data of game objects within a defined volume (which is specified using a shape component). to Nav Mesh component to be processed into Recast data.
- This component requires a shape component for defining the area it operates in.
- If the Navigation Mesh component is configured to build navigation mesh from tiles, Surveyor component will provide the object triangle data in tile volumes, as necessary.

![image](https://user-images.githubusercontent.com/5432499/168393865-a17c7aa5-2124-432a-a1a9-73311e156c56.png)

#### Navigation Detour Component
- This component provides API for finding paths within a given navigation mesh.
- Detour component has a configurable AZ::EntityId field that points to an entity with Navigation Mesh component that will be used for finding paths.

Here is an entity with the navigation components.
![image](https://user-images.githubusercontent.com/5432499/168396596-c63ebc7c-cb89-441e-8c5b-9f216387adc1.png)

#### Data Flow
All the data is processed within the game application (the Editor or a game/server launcher.) No network communication is involved. 
![image](https://user-images.githubusercontent.com/5432499/168394056-089e70ef-14b1-4e2e-8c6c-82a8db2f836e.png)

### What are the advantages of the feature?

- Quick implementation of navigation path features by leveraging code from open source.
- Recast is a stable widely used navigation library.

### What are the disadvantages of the feature?

- The limitation of this feature are the same limitations of Recast library. We do have ability to modify it since it is open source but it may take time to understand the library code.

### How will this be implemented or integrated into the O3DE environment?

- As a core O3DE Gem that consumes code from Recast library using CMake FetchContent functionality.

### Are there any alternatives to this feature?

- Write our own navigation code, which will take a lot more time and effort.
- Integrate another open source navigation solution. I've not found any other good alternatives to Recast that are open source.
- Kythera AI is a commercial solution that provides all the features in this RFC and a lot more!

### How will users learn this feature?

- Through a gem documentation on o3de.org and a blog to be written about the new incoming blog on https://www.o3de.org/blog/.

### Are there any open questions?

- Recast navigation mesh is unique per agent type. So for example, if one needs to calculate paths for different agent sizes, then one has to build a navigation mesh to each agent size type. Recast does not provide a way to calculate a single navigation mesh for any size of an agent. This is probably reasonable given technical limitations and optimizations.

**Comment by AMZN-alexpete** [comment]
Great to see this going in
1. What about breaking the Agent info out into some kind of data class that can be shared between navigation components? Usually in a game you have few agent types but may have many navigation areas spread out all over and being able to change the settings for a single agent type used across multiple navigation areas (and levels) can be handy - this was something Lumberyard implemented by declaring the Agent types in some .xml file with the specifics.  This could also be achieved by using prefabs with overrides once that is supported and if the user remembers to use prefabs, but that may not be the most user friendly option.
2. Consider adding appropriate suffixes to all the component fields so it is clear that the player's height is in meters etc.
3. How does a user define an exclusion (unwalkable) area of the nav mesh? https://docs.aws.amazon.com/lumberyard/latest/userguide/component-nav-area.html#component-nav-area-exclusion
4. Does the navigation mesh consider the 'static' transform option to determine if an object should be included in the navmesh?  There may be a case where a user wants to have an object with static physics that does not affect the nav mesh, like an energy shield that can block bullets, but that AI can navigate through.
5. Consider ways to implement the system so it would be easy to upgrade to Kythera AI - here's a link to the navigation components for Kythera https://www.o3de.org/docs/user-guide/gems/reference/kythera-ai/navmesh-generation/

**Comment by AMZN-Olex** [comment]
> Great to see this going in
> 
> 1. What about breaking the Agent info out into some kind of data class that can be shared between navigation components? Usually in a game you have few agent types but may have many navigation areas spread out all over and being able to change the settings for a single agent type used across multiple navigation areas (and levels) can be handy - this was something Lumberyard implemented by declaring the Agent types in some .xml file with the specifics.  This could also be achieved by using prefabs with overrides once that is supported and if the user remembers to use prefabs, but that may not be the most user friendly option.
> 2. Consider adding appropriate suffixes to all the component fields so it is clear that the player's height is in meters etc.
> 3. How does a user define an exclusion (unwalkable) area of the nav mesh? https://docs.aws.amazon.com/lumberyard/latest/userguide/component-nav-area.html#component-nav-area-exclusion
> 4. Does the navigation mesh consider the 'static' transform option to determine if an object should be included in the navmesh?  There may be a case where a user wants to have an object with static physics that does not affect the nav mesh, like an energy shield that can block bullets, but that AI can navigate through. Actually, probably using Kythera's approach of using a physx collision group is better, if a user can specify an optional physx collision group then they are not limited to the "static" physx collision types.
> 5. Consider ways to implement the system so it would be easy to upgrade to Kythera AI - here's a link to the navigation components for Kythera https://www.o3de.org/docs/user-guide/gems/reference/kythera-ai/navmesh-generation/

Great questions! @AMZN-alexpete 

1. I have thought about that, however, at the moment the only component that needs that data is Navigation Mesh component. Detour (path finding) does not rely on that info but relies on the configuration within the navigation mesh itself. I can see different meshes sharing the same configuration, so perhaps that would work. I know [Kythera uses XML configuration](https://www.o3de.org/docs/user-guide/gems/reference/kythera-ai/navmesh-generation/#configuration) but I have reservation against that as it is not very readable and harder on the User Experience. I would love to go through the UX review of this. To me it seems like keeping those values on a mesh component or a configuration component that it takes the config from is easier for user to discover and configure.
2. With that in mind, I have [added suffixes](https://github.com/o3de/o3de/pull/9562/files#diff-ec24b1412379c04fddbaca767f62b913e10594a9e5ad407eb89944b46b1e9e8a) in the Editor. Here is an example in the current PR.
![image](https://user-images.githubusercontent.com/5432499/168711374-81874f55-9ed4-45c5-bddd-ecd5b05a4f21.png)
3. That can be done through Recast concept of an [obstacle API](https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/DetourTileCache/Include/DetourTileCache.h#L146) We would need to add another component that would turn a shape into an obstacle, for example a RecastObstacleComponent. That does require an introduction of another Recast API - [`dtTileCache`](https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/DetourTileCache/Include/DetourTileCache.h#L107), which I have not done yet in order to reduce the initial complexity. Given enough time, I would love to do so, though, or have someone help out with the implementation. ;) A sample implementation can be found [here](https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/RecastDemo/Include/Sample_TempObstacles.h).
4. Navigation Mesh component does not collect the geometry. That job is delegated to [surveyor API](https://github.com/o3de/o3de/pull/9562/files#diff-68daa7940ca3077e2e54a02c5a45e21a49d4d69dd0362278e13efaa0cccf2410 ), which is implemented as [a separate component](https://github.com/o3de/o3de/pull/9562/files#diff-4b300b35eadaadc3fe9f94267e45af5d4103b9efe00a11fe40d8cd76a8bfe7d8), or can be provided by a user component where they can collect geometry in their own way. My vision is to provide the most common scenario and make it easy to empower users to provide their own geometry collection logic. [The current implementation](https://github.com/o3de/o3de/pull/9562/files#diff-0a489835bf389902190954d38f9bc67cc47fb1808fe953fce28dcbacb5af1992) in the first PR considers physx static shapes only. I believe that is the simplest starting point. One could add invisible walls this way without any visual mesh. ( Kythera, for example, takes the same approach and then adds filtering based on [collision groups](https://www.o3de.org/docs/user-guide/gems/reference/kythera-ai/navmesh-generation/#filter-physics-objects-for-navmesh-generation).  )
5. Unfortunately, Kythera's documentation provides little insight into their components. I don't have access to their gem either, but I would love to learn about their system without exposing myself to their source code.

**Comment by hultonha** [comment]
6 maintainers in attendance at sig-simulation - approval discussed. 5 in favor (not including RFC author).

Approving RFC so navigation gem can be included in O3DE.

Did discuss UX details (e.g. naming of 'Surveyor') - Agreed these smaller details can be refined after initial delivery with with sig-ui-ux.
