### ISSUE TITLE
SIG Reviewer Nomination - amzn-ahmadkrm

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-simulation#12]
### Reviewer Nomination Requirements

* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

### Reviewer Nomination

I would like to nominate: ***`amzn-ahmadkrm`***, to become a ***`Reviewer`*** on behalf of ***`sig-simulation`***.

Not all prerequisites are met to the letter, but will be very soon.

* Nominee's GitHub Profile **https://github.com/amzn-ahmadkrm**

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lgleim** [comment]
Discussed in today's SIG-Simulation Governance meeting. 
`amzn-ahmadkrm` does not currently meet the requirements. 
If conditions are met in the future, the nomination will be approved.

**Comment by hultonha** [comment]
As a sig-simulation maintainer I approve this nomination (as of 2022/08/11) @amzn-ahmadkrm has 4 successful PRs accepted and 2 in review. By next meeting the 6 required contributions should have been met and review privileges can be granted. (see https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Aamzn-ahmadkrm+is%3Aclosed for details). Thanks!

**Comment by moraaar** [comment]
As a sig-simulation reviewer I approve this nomination as well when the 6 contributions requirement is met (4 done, 2 in progress)

**Comment by greerdv** [comment]
As a maintainer, I'm happy to approve this nomination.

**Comment by hultonha** [comment]
I'm am supportive of this nomination and @amzn-ahmadkrm now meets the requirements for becoming an O3DE reviewer

**Comment by hultonha** [comment]
See merged PRs from @amzn-ahmadkrm that show contributions meet reviewer requirements - https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Aamzn-ahmadkrm+is%3Aclosed

**Comment by hultonha** [comment]
@epsilon-delta or @lgleim - could you please approve as a sig-simulation chair as well please? Thanks!

**Comment by hultonha** [comment]
This is now approved
