### ISSUE TITLE
SIG-Simulation meeting agenda for 2022/09/08

### ISSUE THREAD

**Issue by lgleim** [o3de/sig-simulation#19]
## Meeting Details

- **Date/Time:** [2022/09/08 @ 15:30 (24-hour) UTC](https://lists.o3de.org/g/o3de-calendar/viewevent?repeatid=44250&eventid=1557329&calstart=2022-07-14)
- **Location:** [Discord SIG-Simulation Voice Room](https://discord.gg/QqvyuMAc9g)
- **Moderator:** TBA
- **Note Taker** TBD

The [SIG-Simulation Meetings](https://github.com/o3de/sig-simulation/issues?q=is%3Aissue+in%3Atitle+%22SIG-Simulation+meeting+agenda%22+sort%3Acreated-desc) issues contain information on past calls, including agenda, notes, and resources.

## SIG Updates

What happened since the last meeting?

## Meeting Agenda

* Revisit https://github.com/o3de/sig-simulation/issues/12
* Call to action:
  * [Feature grid](https://github.com/o3de/community/blob/main/features/sigjson/sig-simulation-features.json) update
  * Tagging of notable contributions for the next O3DE release
* Discussion
  * How to approach improving the Asset Importing workflow (e.g. coordination with sig/content re asset importer)
  * Reasons for many issues re coordinate system & transformations
  * Workflow for changes that impact serialization (e.g. https://github.com/o3de/o3de/issues/10838) - Start RFC re integrating version numbers into the JSON serialization?
* Planning for 2023

## Outcomes from Discussion topics

Discuss outcomes from agenda

## Action Items

Create actionable items from proposed topics

## Open Discussion Items

List any additional items below

**Comment by lgleim** [comment]
* The reviewer nomination of https://github.com/o3de/sig-simulation/issues/12 was approved
* Notable contributions will be linked in https://github.com/o3de/sig-release/blob/main/releases/22.10.0/22100%20feature%20list.md
* The remaining topics will be revisited in the next governance meeting

**Comment by hultonha** [comment]
Minor update on this ticket (thanks for adding the additional points @lgleim).

In the last governance meeting (2022/09/08) as there was low attendance not much was discussed with focus shifting to issue triage. The SIG reviewer nomination of @amzn-ahmadkrm was approved though. We're hopefully over the next few months they will be able to move to maintainer status as well.

In the meantime I'll do my best to add some links to PRs/Roadmap items for the upcoming 22.10 release but this might not be until later in September (time permitting). Thanks!
