### ISSUE TITLE
Add support for PhysX 5 to O3DE

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-simulation#31]
# Add support for PhysX 5 to O3DE

### Summary

We (Game Engine and Developer Services (GE&DS), part of AWS) would like to upgrade the O3DE physics backend (currently in the form of the PhysX Gem) from PhysX 4.1 to PhysX 5.1. 

### What is the relevance of this feature?

PhysX 4.1 is now end of life (EOL) and will receive no further updates or improvements from NVIDIA. On 2022/11/08 NVIDIA announced that they were [open sourcing PhysX 5](https://developer.nvidia.com/blog/open-source-simulation-expands-with-nvidia-physx-5-release/), the successor to PhysX 4. PhysX 5 had been closed source for some time and it wasn't clear if NVIDIA had plans to make it available to the open source community. The news of PhysX 5 going open source was greeted with much excitement from the community and we would like to adopt it soon so customers of O3DE can benefit from the feature set and performance improvements. It also future proofs O3DE by relying on a current technology that will continue to improve.

Note: PhysX 5 does come with a host of new GPU/CUDA specific features that are out of scope of the RFC. We interested in the core library updates for O3DE.

### Feature design description

Upgrade the current [PhysX Gem](https://github.com/o3de/o3de/tree/development/Gems/PhysX) from PhysX 4.1 to PhysX 5.1. This should be a largely invisible update without many users being impacted.

### Technical design description

We first need to add support for the platforms widely supported by O3DE that are missing from PhysX 5 today (most notably Android, iOS and macOS). We are in discussions with NVIDIA about adding support for these platforms upstream but can also in the short-term create patches to add this platform support.

See open PRs so far that are already in progress (thanks to @moraaar)

- https://github.com/NVIDIA-Omniverse/PhysX/pull/51
- https://github.com/NVIDIA-Omniverse/PhysX/pull/49
- https://github.com/NVIDIA-Omniverse/PhysX/pull/40

There have been some small API changes (most notably to the scene query API) but nothing that breaks compatibility in many places across the engine. A deprecation/upgrade notice will be issued for the next release and an upgrade guide will be created to help users upgrade/migrate if they do experience any breaking changes.

### What are the advantages of the feature?

- Improved performance
- More features
- Continued support/development on the library from NVIDIA

### What are the disadvantages of the feature?

- No native platform support for Android, iOS, macOS (yet)
  - (This is being added now but will need to be maintained by O3DE in the short-term)
- Breaking API changes that may impact some customers

### How will this be implemented or integrated into the O3DE environment?

- PhysX 5.1 will be added as a new third party library to the O3DE ecosystem
- The PhysX Gem will be updated (in-place) to use PhysX 5.1 as its backend as opposed to PhysX 4.1

### Are there any alternatives to this feature?

- Yes
  - Stay with PhysX 4.1. This is an option but does not set up O3DE for success long-term
  - Look to adopt another physics backend to replace or augment PhysX
    - This is a much larger effort with significantly more complexity so should be considered a longer-term goal outside the scope of this RFC.
  - It may be possible to add PhysX 5 as a new separate Gem in addition to PhysX 4
    - This comes with its own set of challenges and could result in customer confusion and configuration problems. It also will be an additional support burden instead of a like for like swap. 

### How will users learn this feature?

- Users' experience of O3DE will remain largely unchanged. Docs referring to old APIs will be updated as well as an upgrade guide for the next O3DE release to help users migrate if they're relying on any PhysX 4.1 functionality that has changed or been removed.

### Are there any open questions?

- Who else might help with this effort
- Will NVIDIA add Android/iOS/macOS support
- What else will we be missing out on if we don't upgrade
- This effort will not add support for _all_ new PhysX 5 features (though customers could access them in some contexts if they wish). We are looking to replicated existing functionality we have today in PhysX 4.1

**Comment by moraaar** [comment]
I support this RFC. It covers well the upgrade to PhysX 5.1. Thanks @hultonha

**Comment by SergeyAMZN** [comment]
+1 
Looks like a great improvement!

**Comment by greerdv** [comment]
+1
Nice work on the RFC!

**Comment by AMZN-alexpete** [comment]
Very cool! Really looking forward to this 😎

**Comment by adamdbrw** [comment]
Excellent! I would love to be able to compare "before" and "after" on some dedicated benchmark scene - we could quantify how impactful the change is and encourage users to switch to the new release when it comes with 5.1.

**Comment by invertednormal** [comment]
+1, agree with @adamdbrw, it'd be great to know the before/after perf difference.

**Comment by epsilon-delta** [comment]
+1

**Comment by lgleim** [comment]
Thanks @hultonha for preparing this RFC! This is looking great and I added it to the agenda for the upcoming governance meeting. One open question that remains for me is how we would proceed in case Nvidia does not accept the patches for Android/iOS/macOS support. If they don't, would the NVIDIA license allow us to maintain a separate distribution incorporating these changes?

**Comment by hultonha** [comment]
> Thanks @hultonha for preparing this RFC! This is looking great and I added it to the agenda for the upcoming governance meeting. One open question that remains for me is how we would proceed in case Nvidia does not accept the patches for Android/iOS/macOS support. If they don't, would the NVIDIA license allow us to maintain a separate distribution incorporating these changes?

No problem! So in the case that NVIDIA don't accept the PRs it's actually okay, it just makes our life a little more difficult. Basically every time NVIDIA update PhysX 5, we have to update (rebase) our patches again on top of their changes, and then rebuild our own third-party package. It just makes things a bit more fiddly but is doable. Please correct me if I'm wrong @moraaar who knows more about this than me! 😅

**Comment by moraaar** [comment]
@hultonha is correct, the PRs we submitted to nVidia repo will always be available for our [3rdParty build scripts](https://github.com/o3de/3p-package-source/pull/165) to use, unless nVidia deletes their whole github repo or something drastic like that (extremely unlikely).

> every time NVIDIA update PhysX 5, we have to update (rebase) our patches again on top of their changes

Just for the record, we would only do this when WE (sig-simulation) decide we want to update PhysX Gem to use the latest updates of PhysX 5, which we may decide it's not worth our effort. So we do have certain control there as well, it'd depend if we'd like to bring certain new features or critical bug fixes.

> would the NVIDIA license allow us to maintain a separate distribution incorporating these changes?

I'm not a lawyer, but I think PhysX5's [BSD3 open source license](https://github.com/NVIDIA-Omniverse/PhysX/blob/release/104.1/LICENSE.md) is ok with that, otherwise we couldn't do it now :)

**Comment by lgleim** [comment]
Perfect, I didn't realize that PhysX 5 now uses a plain BSD3 license without the typical NVIDIA restrictions. Based on the collected feedback, I (as SIG Simulation chair) would like to move this RFC forward to the final comment stage and give the community 5 more days to raise further comments or concerns. I will also crosspost this to Discord for visibility.

**Comment by hultonha** [comment]
Fantastic to hear! 🥳 Thank you very much @lgleim 🙂

**Comment by lgleim** [comment]
As no further concerns have been raised, this RFC is now approved. The initial realization is being tracked in https://github.com/o3de/o3de/pull/13802 based on a community-maintained PhysX 5 fork with mac/ios/android platform support that has been created at https://github.com/o3de/PhysX
More details on this discussion: https://github.com/NVIDIA-Omniverse/PhysX/discussions/58#discussioncomment-4470126
