### ISSUE TITLE
Extend SIG-Simulation charter to include Robotics Simulation

### ISSUE THREAD

**Issue by spham-amzn** [o3de/sig-simulation#33]
Per discussions from the [sig-simulation governance meeting 2022-12-01](https://github.com/o3de/sig-simulation/issues/30), this is a request to update the sig-simulation charter to include Robotic Simulation related projects to the scope of the charter.

Current this includes:
* ROS2 Gem
* Robot Vacuum Sample Project
* Fruit Picking Agricultural Sampe Project

**Comment by hultonha** [comment]
Also tagging @o3de/sig-core for visibility just so they can confirm that they're happy with this move too (tagging @amzn-pratikpa and @lumberyard-employee-dm for visibility if you could please confirm). Thanks!

**Comment by lumberyard-employee-dm** [comment]
Well currently the ROS2 Gem and their sample project is not under ownership of any sig group including SIG-Core.

So the SIG-Core group opinion doesn't hold anymore weight than other sig groups.
That being said we are good with the gem and the sample projects being owned by SIG-Simulation group.

**Comment by lgleim** [comment]
As chair of SIG Simulation, I support both the motion to extend the scope of our SIG to include robotics simulation-related topics as well as the integration of the ROS2 Gem and sample repositories. Thanks for driving these topics forward @hultonha @spham-amzn !

**Comment by hultonha** [comment]
> As chair of SIG Simulation, I support both the motion to extend the scope of our SIG to include robotics simulation-related topics as well as the integration of the ROS2 Gem and sample repositories. Thanks for driving these topics forward @hultonha @spham-amzn !

Fantastic to hear! Thanks @lgleim 🥳

**Comment by hultonha** [comment]
Now this has been approved (I think, checking with @lgleim), can @spham-amzn create a PR with a change to the charter to reflect this? That seems like the next logical step to me? Thanks!
