### ISSUE TITLE
SIG Reviewer Nomination - Paweł Budziszewski (@pawelbudziszewski)

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-simulation#43]
### Reviewer Nomination Requirements

* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

I would like to nominate: Paweł Budziszewski (@pawelbudziszewski), to become a `Reviewer` on behalf of  `sig-simulation`. I verify that they have fulfilled the prerequisites for this role (see above).

### PRs

- https://github.com/o3de/ROSConDemo/pulls/pawelbudziszewski
- https://github.com/o3de/o3de-extras/pulls/pawelbudziszewski
- https://github.com/o3de/o3de/pulls/pawelbudziszewski

### Details

- Nominee's GitHub Profile: https://github.com/pawelbudziszewski

_Reviewers & Maintainers that support this nomination should comment in this issue._

Tagging @lgleim, @epsilon-delta, @moraaar, @greerdv, @SergeyAMZN for visibility.

**Comment by lgleim** [comment]
I support this nomination.

**Comment by SergeyAMZN** [comment]
+1, I support this nomination

**Comment by greerdv** [comment]
I support this nomination as well.

**Comment by moraaar** [comment]
I also support this nomination.

**Comment by lgleim** [comment]
Approved in today's SIG Simulation governance meeting.

**Comment by amzn-changml** [comment]
Invited to the SIG Simulation reviewer team
