### ISSUE TITLE
SIG Maintainer Nomination - Steve Pham (@spham-amzn)

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-simulation#45]
### Maintainer Nomination Requirements

* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

I would like to nominate: Steve Pham (@spham-amzn), to become a `Maintainer` on behalf of  `sig-simulation`. I verify that they have fulfilled the prerequisites for this role (see above).

### PRs

- https://github.com/o3de/ROSConDemo/pulls/spham-amzn
- https://github.com/o3de/o3de-extras/pulls/spham-amzn
- https://github.com/o3de/o3de/pulls/spham-amzn

### Details

- Nominee's GitHub Profile: https://github.com/spham-amzn

_Reviewers & Maintainers that support this nomination should comment in this issue._

Tagging @lgleim, @epsilon-delta, @moraaar, @greerdv, @SergeyAMZN for visibility.

**Comment by smurly** [comment]
I support this

**Comment by lgleim** [comment]
Approved in today's SIG Simulation governance meeting.
