### ISSUE TITLE
Link in Physics Ragdoll workflow leads to non-existing page

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/sig-simulation#50]
**Describe the issue**
The [Ragdoll Authoring Improvements Workflow Tests](https://github.com/o3de/sig-simulation/blob/main/testing-guidance/workflow-tests/physics/physics-ragdoll-workflows.md#general-docs) section has a hyper link ([Creating and Simulating a PhysX Ragdoll](https://www.o3de.org/docs/user-guide/visualization/animation/animation-editor/creating-and-simulating-physx-ragdoll/)) that leads to non-existing page.
Please note that this issue should be consider as a Major.

**Impacted page(s)**
[Physics Ragdoll workflow](https://github.com/o3de/sig-simulation/blob/main/testing-guidance/workflow-tests/physics/physics-ragdoll-workflows.md#ragdoll-authoring-improvements-workflow-tests)

**Expected experience**
All links in the Physics Ragdoll workflow should lead to a proper documentation page.

**Comment by moraaar** [comment]
Tagging @FuzzyCarterAWS

**Comment by LB-MichalRodzos** [comment]
Issue verified as fixed. The [Physics Ragdoll workflow](https://github.com/o3de/sig-simulation/blob/main/testing-guidance/workflow-tests/physics/physics-ragdoll-workflows.md#ragdoll-authoring-improvements-workflow-tests) page contains five working links that leads to proper documentation.
