### ISSUE TITLE
[RFC] ROS2 Gem - Modular Manipulation Components Architecture

### ISSUE THREAD

**Issue by danielemorra98** [o3de/sig-simulation#54]
## Summary

This RFC thus proposes the introduction of an intermediary lower-level manipulation API and Bus, separating the existing Manipulation logic into two different components: 

* one responsible for the _dynamics_, and 
* the other for the _control_ of manipulators in O3DE. 

### What is the relevance of this feature?
To support the simulation of robotic manipulators within O3DE, https://github.com/o3de/o3de-extras/pull/161 is introducing a high-level API for interfacing with the ROS2 / MoveIt ecosystem based on the design described in https://github.com/o3de/o3de-ros2-gem/pull/226 on the level of ROS2 `JointTrajectoryMessages`.
While this API is quite suitable for application-level (e.g. pick & place tasks) work, it does not allow for interfacing (and thus development and testing) of lower-level control methods and applications. 
Introducing an intermediary abstraction layer would allow for manipulator control to be carried out in different ways and simplify the development and testing of future higher-level controllers/interfaces.

### Feature design description
The current design exclusively exposes control of manipulators on the level of JointTrajectoryControl messages as illustrated in this graphic:
![current_architecture](https://raw.githubusercontent.com/o3de/o3de-ros2-gem/manipulation_feature_design/docs/design/manipulation/manipulation_minimal.svg)

Implementing this RFC would introduce an abstraction layer for the low-level control of manipulators and other kinematic chains enabling effort/velocity-based control through an EventBus besides the currrently implemented high-level TrajectoryControl API. This a) enables the development and testing of low-level control methods in O3DE and b) make it easier to expose additional high-level controllers within O3DE for application developers by reusing the existing low-level API.

## Technical design description

To realize this abstraction, the logic already employed by the Vehicle Dynamics & Control module should be adopted and adapted to manipulation. 
Subsequently, two new components would be implemented inside the [ROS2 Gem](https://github.com/o3de/o3de-extras/tree/development/Gems/ROS2) in order to provide useful interconnection with external ROS2 packages.
The `ManipulatorControllerComponent` would handle the **Control** and the `ManipulatorModelComponent` the **Dynamics** of manipulation.

#### High Level Control
In order to differentiate between different inputs sent to the controller, the `ManipulatorControllerComponent` could have a switch between:

- a ROS2 Subscription handler for a unique target joints state (e.g. given by the [JointJog](http://docs.ros.org/en/melodic/api/control_msgs/html/msg/JointJog.html) ROS2 msg)
- a ROS2 Server handler for managing the execution of a trajectory (useful when dealing with some common ROS2 libraries as [MoveIt](https://moveit.picknik.ai/humble/index.html)

#### Low Level Control
In order to tackle different Control algorithm (e.g. PID, Feed-Forward, ...) the `ManipulatorControllerComponent` could offer different implementation of some base member functions to provide the command.

#### Physical properties
A `ManipulatorModelComponent` class could be the base Class for some specific Manipulator model designs such as:
- Robotic arms (Revolute Joints)
- Parallel manipulators (Prismatic joints)

#### Design
Moreover the Dynamics could be moved by different types of PhysX API requests (e.g. the [Joint method](https://github.com/o3de/o3de/blob/development/Gems/PhysX/Code/Include/PhysX/Joint/PhysXJointRequestsBus.h), the [RigidBody method](https://github.com/o3de/o3de/blob/development/Gems/PhysX/Code/Source/RigidBodyComponent.h#L96) and a potential [articulation method](https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/Articulations.html).

![Implementation Logic](https://user-images.githubusercontent.com/48955695/219000539-84703e78-3ca9-4225-b1d0-493d6928e1c2.jpg)

### How will this be work within the O3DE project?

- This new logic will work exactly as the one depicted [here](https://github.com/o3de/o3de-extras/blob/development/Gems/ROS2/docs/design/vehicle_dynamics/diagrams/ROSVehicleDynamics_planned.graphml) conceived for Vehicles simulation. 

### Development
My strategy consists of starting with the development of the `ManipulatorModelComponent`, providing a basic model for robotic arms with only Hinge Joints. From that I will keep on developing the  `ManipulatorControllerComponent` on top of the existing one found in [this PR](https://github.com/o3de/o3de-extras/pull/161).

### Questions/Suggestions
Any comments or doubts about this draft are encouraged. Once agreed with the main structure, I would like to receive feedbacks especially on the the different Manipulators design concepts and if it makes sense building different models according to different joint types.

**Comment by lgleim** [comment]
@adamdbrw @michalpelka Could you please weigh in on this topic at some point if you have the time?

**Comment by hultonha** [comment]
Note: This issue is closely related to articulations (see roadmap initiative - https://github.com/o3de/o3de/issues/14851)

It's possible we should consider using the new upcoming articulation work. This is in-flight at the moment (see https://github.com/aws-lumberyard-dev/o3de/pull/503 for example, the work is going to this staging branch https://github.com/aws-lumberyard-dev/o3de/tree/articulations).

Please also review this RFC covering reduced coordinate articulations - https://github.com/o3de/sig-simulation/issues/60.

If you have any questions about this please ping me @hultonha. I might not be as responsive in the next few weeks though I'm afraid. In that case it might be good to follow-up with @adamdbrw and @michalpelka who will be maintaining the articulation work as well. Thanks!

**Comment by lgleim** [comment]
@adamdbrw I assume this RFC is resolved as of https://github.com/o3de/o3de-extras/pull/366 ?

**Comment by adamdbrw** [comment]
@lgleim that's correct, thank you for noticing. We can close this RFC.
