### ISSUE TITLE
SIG Maintainer Nomination - @amzn-ahmadkrm

### ISSUE THREAD

**Issue by amzn-ahmadkrm** [o3de/sig-simulation#58]
### Maintainer Nomination Requirements

* Has been a Reviewer for 2+ months: 
* 8+ reviewed Pull Requests in the previous 2 months: 
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

### Maintainer Nomination

I would like to nominate: `amzn-ahmadkrm`, to become a `Maintainer` on behalf of `sig-simulation`. I verify that they have fulfilled the prerequisites for this role. 

Reviewer since 15/09/2022: https://github.com/o3de/sig-simulation/issues/12
#### PRs
https://github.com/o3de/o3de/pulls/amzn-ahmadkrm

#### Reviews: 
https://github.com/pulls?q=is%3Apr+reviewed-by%3Aamzn-ahmadkrm

#### Lines changed
[72 commits](https://github.com/o3de/o3de/commits?author=amzn-ahmadkrm)    4,975 ++    3,600 --

Nominee's GitHub Profile: https://github.com/amzn-ahmadkrm

*Reviewers & Maintainers that support this nomination should comment in this issue.*

Tagging @hultonha , @jonawals , @moraaar, @greerdv, @SergeyAMZN for visibility.

**Comment by hultonha** [comment]
I support this nomination

**Comment by SergeyAMZN** [comment]
I support this nomination too

**Comment by moraaar** [comment]
I support this nomination.

**Comment by lgleim** [comment]
Approved in todays SIG Simulation Governance Meeting
