### ISSUE TITLE
SIG Reviewer Nomination: Jackie9527

### ISSUE THREAD

**Issue by thefranke** [o3de/sig-simulation#67]
### Reviewer Nomination Requirements

* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

I would like to nominate: ***`@Jackie9527`***, to become a ***`Reviewer`*** on behalf of ***`sig-simulation`***. I verify that they have fulfilled the prerequisites for this role.

Jackie has been quite instrumental in fixing a whole range of bugs scattered over several SIGs, which you can view here (too many to list):
https://github.com/o3de/o3de/search?p=1&q=Jackie9527&type=commits

* Nominee's GitHub Profile ***`https://github.com/Jackie9527`***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

Tagging @lgleim, @epsilon-delta, @moraaar, @greerdv, @SergeyAMZN for visibility.

**Comment by greerdv** [comment]
I support this nomination, nice work on all those bug fixes.

**Comment by lgleim** [comment]
Awesome! I support this nomination.

**Comment by hultonha** [comment]
I support this nomination as well! Great to hear 🥳

**Comment by thefranke** [comment]
@galibzon Can we close this?

**Comment by galibzon** [comment]
@thefranke , I can't as I don't have this kind of permission for sig-simulation.

**Comment by thefranke** [comment]
Ah pardon, wrong SIG.

**Comment by lgleim** [comment]
Approved and invitation sent as of today's triage meeting.
