### ISSUE TITLE
SIG Maintainer Nomination: Adam Dąbrowski

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/sig-simulation#70]
### Maintainer Nomination Requirements

* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

#### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile

---

I would like to nominate: ***`@adamdbrw`***, to become a ***`Maintainer`*** on behalf of ***`sig-simulation`***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***`https://github.com/adamdbrw`***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by greerdv** [comment]
As a sig-simulation maintainer, I support this nomination.

**Comment by hultonha** [comment]
As a sig-simulation maintainer I also support this nomination
