### ISSUE TITLE
SIG-Simulation Chair/Co-Chair Nominations 2023/04/13-2023/05/10 -- Elections 2023/05/11-2023/05/17

### ISSUE THREAD

**Issue by lgleim** [o3de/sig-simulation#71]
# SIG Simulation chair/co-chair elections for 2023

SIG Simulation is turning one year old in May and it is time to elect the next chair/co-chair, following the [O3DE Elections Guide](https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md).

## The chair/co-chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless **distinctly required**, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, **the chair is considered to be an on-call position during this period.** As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the SIG, the chair will be called to perform a responsibility.

## Responsibilities

* Schedule and proctor regular SIG meetings on a cadence to be determined by the SIG, currently weekly.
* Serve as a source of authority (and ideally wisdom) with regards to O3DE SIG area of discipline. Chairpersons are the ultimate arbiters of many standards, processes, and practices.
* Participate in the SIG Discord channel and on the GitHub Discussion forums.
* Serve as a representative of the broader O3DE community to all other SIGs, partners, the governing board, and the Linux Foundation.
* Represent the SIG to O3DE partners, the governing board, and the Linux Foundation.
* Coordinate with partners and the Linux Foundation regarding official community events.
* Represent (or select/elect representatives) to maintain relationships with all other SIGs as well as the marketing committee.
* Serve as an arbiter in SIG-related disputes.
* Coordinate releases with SIG Release.
* Assist contributors in finding resources and setting up official project or task infrastructure monitored/conducted by the SIG.
* Long-term planning and strategy for the course of the SIG area of discipline for O3DE.
* Maintain a release roadmap for the O3DE SIG area of discipline.

**Additionally**, at this stage of the project, the SIG chairpersons are expected to act in the Maintainer role for review and merge purposes only, due to the lack of infrastructure and available reviewer/maintainer pool.

## Nomination

Nomination may either be by a community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on 2023/05/11.

### Nomination requirements

For this election, nominees are required to have at minimum **two merged submissions to repositories within the [O3DE Github Organization](https://github.com/o3de/)** (must be accepted by 2023/05/17). This is to justify any temporary promotion to Maintainer as required by this term as chairperson. Submissions may be in-flight as of the nomination deadline (2023/05/10 12:00 UTC+1), but the nominee must meet the 2-merge requirement by the end of the election or they will be removed from the results.

The only other nomination requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.

### How to nominate

Nominations will be accepted for 4 weeks from  2023/04/13 12:00 UTC+1 to 2023/05/10 12:00 UTC+1.

Nominate somebody (including yourself) by responding to this issue with:

* A statement that the nominee should be nominated for a chair position in the specific SIG holding its election. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.
* The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
* The GitHub username of the nominee (self-nominations need not include this; it's on your post.)
* Nominee's Discord username (sorry, but you must be an active Discord user if you are a chairperson.)

## Election process

The election will be conducted for one week from 2023/05/11 12:00 UTC+1 and 2023/05/17 12:00 UTC+1 and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and the SIG holding the election may vote. If you choose to vote, we ask that you be familiar with the nominees.

If there is a current (interim) chair, they will announce the results in the Discord SIG channel as well as the SIG O3DE mailing list no later than 2023/05/17 12:00 UTC+1. If there is no (interim) chair, the executive director will announce the results utilizing the same communication channels. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on 2023/06/01 at 12:00 UTC+1. Tentatively SIG chairs will be elected on a **yearly basis**. If you have concerns about wanting to replace chairs earlier, please discuss in the [request for feedback on Governance](https://github.com/o3de/community/discussions/105).

**Comment by adamdbrw** [comment]
I would be interested in **co-chairing** of the simulation group (not sure if I could be available as a **chair** due to time zones and my workloads).

**Comment by Huawei-CarlosCarbone** [comment]
I would like to nominate myself for these elections. Following the required points from this guide I state:

- I understand the responsibilities and requirements of the role, and I will faithfully fulfill them and follow all contributor requirements for O3DE.
- My names and last names are: Carlos Salvador Carbone Lorio, but I may be addressed by my first name Carlos or my first name and first last name Carlos Carbone.
- As a self nomination my github name is implicit but I include here as well for transparency "Huawei-CarlosCarbone".
- My discord user name is: CarlosCarbone [Huawei]#8637.

**Comment by lgleim** [comment]
Based on my tenure chairing SIG-Simulation in the past year, I would like to nominate myself as chair of SIG Simulation: 
Lars Gleim, @lgleim / Lars Gleim [Huawei] on Discord

- I currently fulfill the nomination requirements
- I understand the responsibilities and requirements of the role and commit to faithfully fulfill them
- I commit to following all contributor requirements for O3DE in the process

**Comment by thefranke** [comment]
Hello everyone,

as per Lars' announcement and the O3DE Election Guide the vote is now open until **2023/05/17**:

**Please cast your vote here**:
https://strawpoll.com/polls/e2narqVrAgB

Votes will be anonymous and anyone invested in the direction of O3DE and the SIG holding the election may vote. If you choose to vote, we ask that you be familiar with the nominees. 

**Please only vote once.**

After the deadline results will become public automatically. Thank you!

**Comment by thefranke** [comment]
The poll is now closed. @adamdbrw has been voted for as chair, and @lgleim as co-chair. Do you both accept the new role?

**Comment by adamdbrw** [comment]
@thefranke I do accept, thank you!
I will be on parental leave 24.05-09.06, so I unfortunately need to start the tenure with absence. @lgleim, you will be available though, right?

**Comment by lgleim** [comment]
I accept, thanks @thefranke! I will sync with @adamdbrw offline to get everything else organized.
