### ISSUE TITLE
SIG-Simulation Chair/Co-Chair Nominations 2022/05/02-2022/05/16 -- Elections 2022/05/16-2022/05/23

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-simulation#8]
# SIG Simulation chair/co-chair elections for 2022

With the creation of sig-simulation we need official elections for chair/co-chair roles. @hultonha is acting as an interim chair right now to help setup the SIG. (See [proposed guidance](https://github.com/o3de/community/discussions/105) for more context about the election process).

## The chair/co-chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless **distinctly required**, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, **the chair is considered to be an on-call position during this period.** As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the SIG, the chair will be called to perform a responsibility.

## Responsibilities

* Schedule and proctor regular SIG meetings on a cadence to be determined by the SIG.
* Serve as a source of authority (and ideally wisdom) with regards to O3DE SIG area of discipline. Chairpersons are the ultimate arbiters of many standards, processes, and practices.
* Participate in the SIG Discord channel and on the GitHub Discussion forums.
* Serve as a representative of the broader O3DE community to all other SIGs, partners, the governing board, and the Linux Foundation.
* Represent the SIG to O3DE partners, the governing board, and the Linux Foundation.
* Coordinate with partners and the Linux Foundation regarding official community events.
* Represent (or select/elect representatives) to maintain relationships with all other SIGs as well as the marketing committee.
* Serve as an arbiter in SIG-related disputes.
* Coordinate releases with SIG Release.
* Assist contributors in finding resources and setting up official project or task infrastructure monitored/conducted by the SIG.
* Long-term planning and strategy for the course of the SIG area of discipline for O3DE.
* Maintain a release roadmap for the O3DE SIG area of discipline.

**Additionally**, at this stage of the project, the SIG chairpersons are expected to act in the Maintainer role for review and merge purposes only, due to the lack of infrastructure and available reviewer/maintainer pool.

... And potentially more. Again, this is an early stage of the project and chair responsibilities have been determined more or less ad-hoc as new requirements and situations arise. In particular the **community** half of this SIG has been very lacking due to no infrastructural support, and a chairperson will ideally bring some of these skills.

## Nomination

Nomination may either be by a community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on 2022/05/16.

### Nomination requirements

~~For this election, nominees are required to have at minimum **two merged submissions to [http://github.com/o3de/o3de](https://github.com/o3de/o3de)** (must be accepted by 2022/05/02). This is to justify any temporary promotion to Maintainer as required by this term as chairperson. Submissions may be in-flight as of the nomination deadline (2022/05/16 12:00 UTC+1), but the nominee must meet the 2-merge requirement by the end of the election or they will be removed from the results.~~

~~Any elected chairperson who does not currently meet the Maintainer status will be required to work with contributors from the SIG to produce an appropriate number of accepted submissions by **May 2nd 2022** or they will be removed and another election will be held.~~

> Note: The above stipulation has been relaxed after [discussing with the TSC](https://github.com/o3de/tsc/issues/29#issuecomment-1116207827) to allow a more varied pool of candidates to be nominated.

The only other nomination requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.

### How to nominate

Nominations will be accepted for 2 weeks from 2022/05/02 12:00 UTC+1 to 2022/05/16 12:00 UTC+1.

Nominate somebody (including yourself) by responding to this issue with:

* A statement that the nominee should be nominated for a chair position in the specific SIG holding its election. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.
* The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
* The GitHub username of the nominee (self-nominations need not include this; it's on your post.)
* Nominee's Discord username (sorry, but you must be an active Discord user if you are a chairperson.)

## Election process

The election will be conducted for one week from 2022/05/16 12:00 UTC+1 and 2022/05/23 12:00 UTC+1 and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and the SIG holding the election may vote. If you choose to vote, we ask that you be familiar with the nominees.

If there is a current interim chair, they will announce the results in the Discord SIG channel as well as the SIG O3DE mailing list no later than 2022/05/23 12:00 UTC+1. If there is no interim chair, the executive director will announce the results utilizing the same communication channels. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on 2022/06/01 at 12:00 UTC+1. Tentatively SIG chairs will be elected on a **yearly basis**. If you have concerns about wanting to replace chairs earlier, please discuss in the [request for feedback on Governance](https://github.com/o3de/community/discussions/105).

**Comment by greerdv** [comment]
I would like to nominate @hultonha as chair.

**Comment by hultonha** [comment]
I would like to nominate @greerdv as chair.

**Comment by moraaar** [comment]
I would like to nominate @hultonha and @greerdv for chair and co-chair. Both will do great at either roles.

**Comment by thefranke** [comment]
I'd like to nominate @lgleim (Lars Gleim) for chair of #sig-simulation, and @ManosAgelidis (Emmanouil Angelidis) for co-chair respectively. Both of them are part of our growing O3DE developer group at Huawei.

# Background info

@lgleim is a Senior Research Engineer at the Huawei Munich Research Center where he develops Digital Twin and Simulation technology for robotic applications in manufacturing. In his role, he established Huawei's efforts to develop a robotics simulator based on O3DE. Previously, Lars did his PhD studies in Computer Science at RWTH Aachen University where he captured industrial processes & related data in Knowledge Graphs using concepts from Semantic Data Management & Digital Twin technologies. He successfully lead collaborations with industrial & academic partners in mechanical engineering and enjoys interdisciplinary collaboration. As chair of O3DE SIG Simulation, he would further apply his network and insights into industrial processes, requirements and the "OT mindset" to drive the strategic positioning of O3DE as an open platform for the industrial Metaverse and 3D Digital Twin simulation.

@ManosAgelidis got his diploma (5 years BSc-MSc) in Mechanical Engineering from the National Technical University of Athens, Greece in 2010 and his MSc in Biomedical Engineering from the same University in 2012. He is currently concluding with PhD on the intersection of Robotics / Neuroscience / AI at the Technical University of Munich (TUM) in collaboration with the Ecole Polytechnique Federale de Lausanne (EPFL). He worked as a Software Engineer / Researcher for a research project funded by the EU on the topic of biomechanical / fluid simulation (2012-2015). He was a software architect (2016-2021) of the Neurorobotics Platform, a software developed within the European Horizon 2020 Human Brain Project, focusing on Robotics / AI simulation. His main expertise lies on the topic of physical simulation for robotics. He published an open-source fluid dynamics plugin for the Gazebo robotics simulator. Currently he is a senior robotics research engineer at the Huawei Cloud Robotics team.

**Comment by thefranke** [comment]
Updated the candidate for co-chair.

**Comment by hultonha** [comment]
@spotzz has kindly volunteered to be the impartial election official to oversee the election when it starts next week.

I've also updated this issue to reflect the new guidance on who can be nominated. Thanks!

**Comment by spotz** [comment]
Hey all I need confirmation of acceptance from the following nominated people:

@greerdv @lgleim @epsilon-delta

I'll also post in the Discord channel

**Comment by greerdv** [comment]
I accept the nomination.

**Comment by epsilon-delta** [comment]
@thefranke, thank you very much for your nomination. 
Dear all, I accept the nomination.

**Comment by lgleim** [comment]
I accept the nomination. Thanks @thefranke!

**Comment by spotz** [comment]
Thanks everyone for accepting your nominations. Voting is now open until next Monday at - https://framadate.org/IfFhgOFWOwztSXi4. I will close the poll at 12:00 CST on 5/23

**Comment by hultonha** [comment]
Thanks very much @spotz! 👍

**Comment by aFinchy** [comment]
Hi All, 

The election poll is now closed for the SIG-Simulation chair and co-chair seats. 

The person with the most votes and therefore the new Chair is @lgleim .
The person with the second most votes and therefore the new Co-Chair is @epsilon-delta . 

Congratulations!

@lgleim & @epsilon-delta Can you please provide me with your Discord handle so I can attach the proper roles and obtain some other information?

**Comment by hultonha** [comment]
Closing this issue now the election has concluded. Thanks all for participating! 🙂
