### ISSUE TITLE
SIG Reviewer Nomination: Jan Hanca

### ISSUE THREAD

**Issue by adamdbrw** [o3de/sig-simulation#84]
### Reviewer Nomination Requirements

* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

### Maintainer Nomination Requirements

* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

---

### Reviewer/Maintainer Nomination

---

I would like to nominate: ***`jhanca-robotecai`***, to become a ***`Reviewer`*** on behalf of ***`sig-simulation`***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***`[https://github.com/jhanca-robotecai)`***
* [PRs contributed (to o3de-extras)](https://github.com/o3de/o3de-extras/pulls?q=is%3Apr+author%3Ajhanca-robotecai+is%3Aclosed)

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by pawelbudziszewski** [comment]
I support this nomination.

**Comment by michalpelka** [comment]
I support this nomination.

**Comment by spham-amzn** [comment]
I support this nomination

**Comment by adamdbrw** [comment]
Nomination accepted during the triage meeting.
